### ISSUE TITLE
update to GNOME 3.28 breaks i3-gnome

### ISSUE THREAD

**Issue by killajoe** [mephux/i3-gnome#4]
On Archlinux update to GNOME 3.28 today breaks i3-gnome again as ususal ;)

`Mär 25 10:16:24 empowered64 i3-gnome.desktop[15529]: i3: Cannot open display
Mär 25 10:16:24 empowered64 i3-gnome.desktop[15529]: Failed to open connection to "session" message bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.`

**Comment by mephux** [comment]
I'm guessing this is happening during logout? It could be the code added to
ensure the session is killed.

**Comment by killajoe** [comment]
yes may it is that, this was the only log i find inside the journal what could be related...

**Comment by killajoe** [comment]
But i3-gnome session do not start, it kicks back to login manager (try GDM and LightDM)

**Comment by killajoe** [comment]
here it goes:

`RequiredComponents=i3-gnome;org.gnome.SettingsDaemon.A11ySettings;org.gnome.SettingsDaemon.Clipboard;org.gnome.SettingsDaemon.Color;org.gnome.SettingsDaemon.Datetime;org.gnome.SettingsDaemon.Housekeeping;org.gnome.SettingsDaemon.Keyboard;org.gnome.SettingsDaemon.MediaKeys;org.gnome.SettingsDaemon.Mouse;org.gnome.SettingsDaemon.Power;org.gnome.SettingsDaemon.PrintNotifications;org.gnome.SettingsDaemon.Rfkill;org.gnome.SettingsDaemon.ScreensaverProxy;org.gnome.SettingsDaemon.Sharing;org.gnome.SettingsDaemon.Smartcard;org.gnome.SettingsDaemon.Sound;org.gnome.SettingsDaemon.Wacom;org.gnome.SettingsDaemon.XSettings;`

**Comment by tonylambiris** [comment]
@killajoe can you grab the latest commit and see if that works?

Thanks.
